server:
  port: 9891

spring:
  redis:
    timeout: 10000  # 连接超时时间（毫秒）
# 单机模式
#    host: 106.14.146.229
#    port: 6379
    password: 123456
#哨兵模式

    sentinel:
      password: 123456
      master: mymaster
      nodes:
        - 106.14.146.229:6384
        - 106.14.146.229:6383

    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接

  cache:
    redis:
      time-to-live: 600m